### ISSUE TITLE
Tweak suggestion

### ISSUE THREAD

**Issue by Hydci** [johnzaro/cydia#10]
Hello,
Would it be possible to have a tweak that returns to the message list when we close the application? much like the popper message tweak did.
http://moreinfo.thebigboss.org/moreinfo/depiction.php?file=messagepopperDp

someone did a port for ios 13 but does not work on ios 13.5
https://www.reddit.com/r/jailbreak/comments/fbmx14/request_messagepopper_update_for_ios_13/

**Comment by johnzaro** [comment]
Yes I’ll see if I can create a working alternative

**Comment by johnzaro** [comment]
i uploaded a new tweak called perfectMessages for the feature you requested, try it and tell me if it works for you
