### ISSUE TITLE
Zebra: “Failed to Add Source”

### ISSUE THREAD

**Issue by JagandeepBrar** [johnzaro/cydia#9]
It appears to be working through Cydia without an issue, but Zebra is throwing me this error:

![image](https://user-images.githubusercontent.com/3048295/84286661-9d918500-ab04-11ea-9167-b29c21f8638c.png)

Was added and being used with no problems until this morning, last I checked Zebra was yesterday morning.

**Comment by JagandeepBrar** [comment]
Looks like I am getting a slightly different error now:

![image](https://user-images.githubusercontent.com/3048295/84333850-8085a200-ab56-11ea-857b-5422a2edfeb5.png)

**Comment by PorridgePi** [comment]
Same problem on Zebra. Added your repo a few weeks ago. Today, when I tried to refresh it in Zebra, it shows 404 Not Found. However, it works in Cydia.

iOS 13.5
Zebra 1.2~beta1b

**Comment by johnzaro** [comment]
try the new url johnzaro.github.io/cydia/ tell me if it now works

**Comment by JagandeepBrar** [comment]
@johnzaro That URL works correctly, thanks for the quick resolution!

I’ll let you close the issue when you see fit.
